language: minimal
sudo: false
notifications:
  email: false

env:
  global:
    - GH_PAGES_DIR="$HOME/gh-pages"
    - GFDL_BASE="$HOME/Isca" 
    - GFDL_ENV="$HOME/Isca/src/extra/env/ubuntu_conda"
    - GFDL_WORK="$HOME/gfdl_work"
    - GFDL_DATA="$HOME/gfdl_data"
    - GFDL_PYDIR="$HOME/src/extra/python"

matrix:
  fast_finish: true
  include:
    - env: CONDA_ENV=py37

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a

install:
  - if [[ "$CONDA_ENV" == "py37" ]]; then
      conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml;
    fi;
  - source $GFDL_ENV
  - conda activate test_env
  - conda list
  - cd $GFDL_PYDIR 
  - python setup.py develop

script:
  - if [[ "$CONDA_ENV" == "docs" ]]; then
      echo "NotImplementedYet: here be future docs building command";
    else
      pytest -v;
    fi;

after_success:
  - echo "Success!"
